### ISSUE TITLE
support hapi-pino

### ISSUE THREAD

**Issue by davidmarkclements** [davidmarkclements/pino-trace#1]
(TODO)

In Hapi simply `register` `pino-trace` after `hapi-pino`:

``` js
server.register(require('hapi-pino'), (err) => {
  // etc.
})
server.register(require('pino-trace'))
```

**Comment by davidmarkclements** [comment]
@mcollina could probably do with a convo about this

**Comment by mcollina** [comment]
I think it might be more in the Hapi concept to do either "hapi-pino-trace", or add a `trace: true` flag into hapi-pino. I'm leaning towards this second option.

**Comment by davidmarkclements** [comment]
Cool 2nd op sounds good, I'll close this
